import os
import json
from datetime import datetime
from crewai.tools import BaseTool
from pydantic import BaseModel, Field
from utils.logger import get_logger

logger = get_logger(__name__)


#Input schemas
class WriteFileInput(BaseModel):
    """Input schema for writing files."""
    content: str = Field(
        description="The text content to write to the file"
    )
    filename: str = Field(
        description="Name of the file to write (e.g. 'report.md')"
    )
    subfolder: str = Field(
        default="reports",
        description="Subfolder inside output/ to save to (e.g. 'reports' or 'raw')"
    )


class ReadFileInput(BaseModel):
    """Input schema for reading files."""
    filepath: str = Field(
        description="Full relative path of the file to read (e.g. 'output/reports/report.md')"
    )


#Write tool
class WriteFileTool(BaseTool):
    name: str = "Write File"
    description: str = (
        "Saves text content to a file in the output directory. "
        "Use this to save research findings, analysis results, or final reports. "
        "Specify a filename and optionally a subfolder ('reports' or 'raw')."
    )
    args_schema: type[BaseModel] = WriteFileInput

    def _run(self, content: str, filename: str, subfolder: str = "reports") -> str:
        """Writes content to a file, creating directories if needed."""

        #Ensure output directory exists
        output_dir = os.path.join("output", subfolder)
        os.makedirs(output_dir, exist_ok=True)

        #Add timestamp to filename to avoid overwrites
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        name, ext = os.path.splitext(filename)
        if not ext:
            ext = ".md"  # default to markdown if no extension given
        timestamped_filename = f"{name}_{timestamp}{ext}"#each report will have assigned with unique names automatically
        filepath = os.path.join(output_dir, timestamped_filename)

        #Write file
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"File written: {filepath}")
            return f"SUCCESS: File saved to '{filepath}'"

        except OSError as e:
            logger.error(f"Failed to write file: {e}")
            return f"ERROR: Could not write file - {str(e)}"


#Read tool
class ReadFileTool(BaseTool):
    name: str = "Read File"
    description: str = (
        "Reads and returns the content of a file. "
        "Use this to load previously saved research or reports. "
        "Provide the full relative path to the file."
    )
    args_schema: type[BaseModel] = ReadFileInput

    def _run(self, filepath: str) -> str:
        """Reads a file and returns its content."""
        logger.info(f"Reading file: {filepath}")

        #Validate file exists
        if not os.path.exists(filepath):
            logger.warning(f"File not found: {filepath}")
            return f"ERROR: File not found - '{filepath}'"

        #Read file
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
            logger.info(f"Read {len(content)} characters from {filepath}")
            return f"Content of '{filepath}':\n\n{content}"

        except OSError as e:
            logger.error(f"Failed to read file: {e}")
            return f"ERROR: Could not read file - {str(e)}"


#Test module
if __name__ == "__main__":
    #Test write
    write_tool = WriteFileTool()
    result = write_tool._run(
        content="# Test Report\n\nThis is a test report generated by the crew.",
        filename="test_report.md",
        subfolder="reports"
    )
    print(result)

    #Test read
    read_tool = ReadFileTool()
    #Extract filepath from the write result
    filepath = result.replace("SUCCESS: File saved to '", "").replace("'", "")
    print(read_tool._run(filepath))